name: CI Jobs

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: number

jobs:
  test:
    name: Tests should pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ inputs.node-version }}
      - name: Test
        run: just test

  build:
    name: Build should work
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ inputs.node-version }}
      - name: Prepack
        run: just prepack
      - name: Run esm
        run: node dist/Main.js
      - name: Run cjs
        run: node dist/Main.cjs
